name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    # Checkout the code
    - name: Checkout code
      uses: actions/checkout@v4
    # Install dependencies
    - name: Install dependencies
      run:  sudo apt-get update && sudo apt-get install -y gcc make libcriterion-dev
    # Test project
    - name: Run tests
      run: make test
